# Required settings
name: Sarah Jeong
url: https://sarahjeong.github.com # No trailing slash
# .github.com will redirects to .github.io fwiw

# Optional settings
description: ""
ga: UA-XXXXXXXX-Y
use_css: true

# Advanced settings
data_dir: data
markdown: kramdown
exclude:
    - "*.md"
