title: ""
description: ""
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://sarahjeong.github.io
data_source: data

# Build settings
markdown: kramdown

exclude:
    - ".*" # Automatic, but just in case
    - "*.log"
    - "*.md"
