# Required settings
name: Sarah Jeong
url: https://sarahjeong.github.com # No trailing slash

# Optional settings
description: ""
ga: UA-XXXXXXXX-Y
use_css: true

# Advanced settings
data_source: data
markdown: kramdown
exclude:
    - ".*" # Automatic, but just in case
    - "*.log"
    - "*.md"
