# Required settings
name: Sarah Jeong
url: https://sarahjeong.github.com # No trailing slash
# .github.com will redirects to .github.io fwiw

# Optional settings
archive_symbol: "(a)"
description: ""
ga: UA-XXXXXXXX-Y
use_css: true
quotes:
    left: "&ldquo;"
    right: "&rdquo;"

# Advanced settings
data_dir: data
exclude:
    - "*.md"
markdown: kramdown
